name: Model Architecture Tests

on: [push, pull_request]

jobs:
  test:
    name: Check Model Architecture Requirements
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.0.1 torchvision==0.15.2 tqdm torchsummary

    - name: Create data directory
      run: |
        mkdir -p data

    - name: Run Tests
      run: |
        python test.py